"""Add rich profile fields to User and DoctorProfile

Revision ID: 25aa9b3f9e44
Revises: 6ad41a34883c
Create Date: 2025-12-22 08:53:20.290793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25aa9b3f9e44'
down_revision = '6ad41a34883c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_methods', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('expertises', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('diplomas', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')

    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.drop_column('diplomas')
        batch_op.drop_column('expertises')
        batch_op.drop_column('payment_methods')
        batch_op.drop_column('languages')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
