"""Add appointment_time and booking_type to Appointment

Revision ID: 346e2d702bd8
Revises: 33bcabff73af
Create Date: 2025-12-21 22:17:57.729406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346e2d702bd8'
down_revision = '33bcabff73af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('booking_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('consultation_reason', sa.String(length=100), nullable=True))
        batch_op.alter_column('queue_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('queue_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('consultation_reason')
        batch_op.drop_column('booking_type')
        batch_op.drop_column('appointment_time')

    # ### end Alembic commands ###
