"""Add unique constraint for scheduled slots

Revision ID: 53df01c59dc1
Revises: 346e2d702bd8
Create Date: 2025-12-21 22:19:41.818631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53df01c59dc1'
down_revision = '346e2d702bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_unique_scheduled_slot', ['doctor_id', 'appointment_date', 'appointment_time'], unique=True, postgresql_where=sa.text("status = 'confirmed' AND appointment_time IS NOT NULL"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_scheduled_slot', postgresql_where=sa.text("status = 'confirmed' AND appointment_time IS NOT NULL"))

    # ### end Alembic commands ###
