"""Add ConsultationType, DoctorAbsence, and user no_show fields

Revision ID: 6ad41a34883c
Revises: 53df01c59dc1
Create Date: 2025-12-21 22:44:59.022083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad41a34883c'
down_revision = '53df01c59dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('is_emergency_only', sa.Boolean(), nullable=True),
    sa.Column('require_existing_patient', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doctor_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'consultation_types', ['consultation_type_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_show_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('no_show_count')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('doctor_notes')
        batch_op.drop_column('consultation_type_id')

    op.drop_table('doctor_absences')
    op.drop_table('consultation_types')
    # ### end Alembic commands ###
