"""Initial migration

Revision ID: 848ef2d605b0
Revises:
Create Date: 2025-12-24 12:30:41.834605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848ef2d605b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epidemiology_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('wilaya', sa.String(length=100), nullable=False),
    sa.Column('pathology_tag', sa.String(length=100), nullable=False),
    sa.Column('age_group', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('no_show_count', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('languages', sa.String(length=255), nullable=True),
    sa.Column('payment_methods', sa.String(length=255), nullable=True),
    sa.Column('expertises', sa.String(length=500), nullable=True),
    sa.Column('diplomas', sa.Text(), nullable=True),
    sa.Column('waiting_room_count', sa.Integer(), nullable=True),
    sa.Column('appointment_mode', sa.Enum('TICKET_QUEUE', 'SMART_RDV', name='appointmentmode'), nullable=True),
    sa.Column('kyc_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='kycstatus'), nullable=True),
    sa.Column('documents_encrypted_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_conditions', sa.Text(), nullable=True),
    sa.Column('vaccines', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('relatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('is_emergency_only', sa.Boolean(), nullable=True),
    sa.Column('require_existing_patient', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('queue_number', sa.Integer(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('appointment_time', sa.Time(), nullable=True),
    sa.Column('booking_type', sa.String(length=20), nullable=True),
    sa.Column('consultation_reason', sa.String(length=100), nullable=True),
    sa.Column('consultation_type_id', sa.Integer(), nullable=True),
    sa.Column('emergency_type_id', sa.Integer(), nullable=True),
    sa.Column('relative_id', sa.Integer(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_type_id'], ['consultation_types.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['emergency_type_id'], ['emergency_types.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['relative_id'], ['relatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_unique_scheduled_slot', ['doctor_id', 'appointment_date', 'appointment_time'], unique=True, postgresql_where=sa.text("status = 'confirmed' AND appointment_time IS NOT NULL"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_scheduled_slot', postgresql_where=sa.text("status = 'confirmed' AND appointment_time IS NOT NULL"))

    op.drop_table('appointments')
    op.drop_table('emergency_types')
    op.drop_table('doctor_availability')
    op.drop_table('doctor_absences')
    op.drop_table('consultation_types')
    op.drop_table('user_relationships')
    op.drop_table('relatives')
    op.drop_table('health_records')
    op.drop_table('doctor_profiles')
    op.drop_table('users')
    op.drop_table('epidemiology_data')
    # ### end Alembic commands ###
