"""add price_paid

Revision ID: 88b63076b530
Revises: 71f45510936c
Create Date: 2025-12-26 15:57:08.436178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b63076b530'
down_revision = '71f45510936c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_doctor_id', sa.Integer(), nullable=False),
    sa.Column('to_doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_doctor_id'], ['doctor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prescription_type', sa.String(length=20), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('max_usage', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_token'), ['token'], unique=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('family_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_treatments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prescriptions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('prescriptions')
        batch_op.drop_column('current_treatments')
        batch_op.drop_column('family_history')
        batch_op.drop_column('emergency_contact')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('price_paid')

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_token'))

    op.drop_table('prescriptions')
    op.drop_table('referrals')
    # ### end Alembic commands ###
