"""add_status_to_prescription

Revision ID: e5a6d0dfdd39
Revises: 88b63076b530
Create Date: 2025-12-31 13:01:44.402313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a6d0dfdd39'
down_revision = '88b63076b530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('security_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_column('security_hash')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
